delete from dbo.MeasurementUnitType

insert into dbo.MeasurementUnitType(MeasurementUnitTypeID, MeasurementUnitTypeName, MeasurementUnitTypeDisplayName, LegendDisplayName, SingularDisplayName, NumberOfSignificantDigits, IsUserSelectable) values 
(1, 'Acres', 'acres', 'acres', 'Acre', 2, 1),
(2, 'Miles', 'miles', 'miles', 'Mile', 2, 1),
(3, 'SquareFeet', 'square feet', 'sq ft', 'Square Foot', 2, 1),
(4, 'LinearFeet', 'linear feet', 'lf', 'Linear Foot', 2, 1),
(5, 'Kilogram', 'kg', 'kg', 'Kilogram', 2, 1),
(6, 'Number', 'number', null, 'Each Unit', 0, 1),
(7, 'Pounds', 'pounds', 'lbs', 'Pound', 2, 1),
(8, 'Tons', 'tons', 'tons', 'Ton', 2, 1),
(9, 'Dollars', 'dollars', null, 'Dollar', 0, 1),
(10, 'Parcels', 'parcels', null, 'Parcel', 0, 1),
(11, 'Percent', '%', '%', '%', 0, 1),
(12, 'Therms', 'therms', 'therms', 'Therm', 2, 1),
(13, 'PartsPerMillion', 'ppm', 'ppm', 'Part Per Million', 3, 1),
(14, 'PartsPerBillion', 'ppb', 'ppb', 'Part Per Billion', 3, 1),
(15, 'MilligamsPerLiter', 'mg/L', 'mg/L', 'Milligram Per Liter', 2, 1),
(16, 'NephlometricTurbidityUnit', 'NTU', 'NTU', 'Nephlometric Turbidity Unit', 1, 1),
(17, 'Meters', 'meters', 'meters', 'Meter', 1, 1),
(18, 'PeriphytonBiomassIndex', 'PBI', 'PBI', 'Periphyton biomass index', 0, 1),
(19, 'AcreFeet', 'acre-feet', 'acre-ft', 'Acre-Foot', 0, 1),
(20, 'Gallon', 'gallons', 'gallons', 'Gallon', 0, 1),
(21, 'CubicYards', 'cubic yards', 'cubic yards', 'Cubic Yard', 0, 1),
(22, 'MetricTons', 'metric tons', 'metric tons', 'Metric Ton', 0, 1),
(23, 'Hours', 'hours ', 'hours', 'Hour', 0, 1),
(24, 'Not Applicable', 'Not Applicable', 'Not Applicable', 'Not Applicable', 0, 0)